// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: custom_comms.proto

package com.skydio.pbtypes.skills;

public final class CustomCommsProto {
  private CustomCommsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CustomRpcRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:skills.CustomRpcRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * utime of the message
     * </pre>
     *
     * <code>int64 utime = 1;</code>
     */
    long getUtime();

    /**
     * <pre>
     * version of the message
     * </pre>
     *
     * <code>int32 version = 2;</code>
     */
    int getVersion();

    /**
     * <pre>
     * A unique id for the request.  This will be copied into the response.
     * </pre>
     *
     * <code>int64 request_id = 3;</code>
     */
    long getRequestId();

    /**
     * <pre>
     * If false, the vehicle won't send a response.
     * </pre>
     *
     * <code>bool ack = 4;</code>
     */
    boolean getAck();

    /**
     * <pre>
     * The key of the skill which will receive this request.
     * If the given skill is not running, an error will be returned.
     * </pre>
     *
     * <code>string skill_key = 5;</code>
     */
    java.lang.String getSkillKey();
    /**
     * <pre>
     * The key of the skill which will receive this request.
     * If the given skill is not running, an error will be returned.
     * </pre>
     *
     * <code>string skill_key = 5;</code>
     */
    com.google.protobuf.ByteString
        getSkillKeyBytes();

    /**
     * <pre>
     * The request data.
     * </pre>
     *
     * <code>bytes data = 6;</code>
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * <pre>
   * An RPC request message containing a skill destination and binary user data
   * </pre>
   *
   * Protobuf type {@code skills.CustomRpcRequest}
   */
  public  static final class CustomRpcRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:skills.CustomRpcRequest)
      CustomRpcRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CustomRpcRequest.newBuilder() to construct.
    private CustomRpcRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CustomRpcRequest() {
      utime_ = 0L;
      version_ = 0;
      requestId_ = 0L;
      ack_ = false;
      skillKey_ = "";
      data_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CustomRpcRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              utime_ = input.readInt64();
              break;
            }
            case 16: {

              version_ = input.readInt32();
              break;
            }
            case 24: {

              requestId_ = input.readInt64();
              break;
            }
            case 32: {

              ack_ = input.readBool();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              skillKey_ = s;
              break;
            }
            case 50: {

              data_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.skydio.pbtypes.skills.CustomCommsProto.internal_static_skills_CustomRpcRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.skydio.pbtypes.skills.CustomCommsProto.internal_static_skills_CustomRpcRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcRequest.class, com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcRequest.Builder.class);
    }

    public static final int UTIME_FIELD_NUMBER = 1;
    private long utime_;
    /**
     * <pre>
     * utime of the message
     * </pre>
     *
     * <code>int64 utime = 1;</code>
     */
    public long getUtime() {
      return utime_;
    }

    public static final int VERSION_FIELD_NUMBER = 2;
    private int version_;
    /**
     * <pre>
     * version of the message
     * </pre>
     *
     * <code>int32 version = 2;</code>
     */
    public int getVersion() {
      return version_;
    }

    public static final int REQUEST_ID_FIELD_NUMBER = 3;
    private long requestId_;
    /**
     * <pre>
     * A unique id for the request.  This will be copied into the response.
     * </pre>
     *
     * <code>int64 request_id = 3;</code>
     */
    public long getRequestId() {
      return requestId_;
    }

    public static final int ACK_FIELD_NUMBER = 4;
    private boolean ack_;
    /**
     * <pre>
     * If false, the vehicle won't send a response.
     * </pre>
     *
     * <code>bool ack = 4;</code>
     */
    public boolean getAck() {
      return ack_;
    }

    public static final int SKILL_KEY_FIELD_NUMBER = 5;
    private volatile java.lang.Object skillKey_;
    /**
     * <pre>
     * The key of the skill which will receive this request.
     * If the given skill is not running, an error will be returned.
     * </pre>
     *
     * <code>string skill_key = 5;</code>
     */
    public java.lang.String getSkillKey() {
      java.lang.Object ref = skillKey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        skillKey_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * The key of the skill which will receive this request.
     * If the given skill is not running, an error will be returned.
     * </pre>
     *
     * <code>string skill_key = 5;</code>
     */
    public com.google.protobuf.ByteString
        getSkillKeyBytes() {
      java.lang.Object ref = skillKey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        skillKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATA_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString data_;
    /**
     * <pre>
     * The request data.
     * </pre>
     *
     * <code>bytes data = 6;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (utime_ != 0L) {
        output.writeInt64(1, utime_);
      }
      if (version_ != 0) {
        output.writeInt32(2, version_);
      }
      if (requestId_ != 0L) {
        output.writeInt64(3, requestId_);
      }
      if (ack_ != false) {
        output.writeBool(4, ack_);
      }
      if (!getSkillKeyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, skillKey_);
      }
      if (!data_.isEmpty()) {
        output.writeBytes(6, data_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (utime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, utime_);
      }
      if (version_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, version_);
      }
      if (requestId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, requestId_);
      }
      if (ack_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, ack_);
      }
      if (!getSkillKeyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, skillKey_);
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, data_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcRequest)) {
        return super.equals(obj);
      }
      com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcRequest other = (com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcRequest) obj;

      boolean result = true;
      result = result && (getUtime()
          == other.getUtime());
      result = result && (getVersion()
          == other.getVersion());
      result = result && (getRequestId()
          == other.getRequestId());
      result = result && (getAck()
          == other.getAck());
      result = result && getSkillKey()
          .equals(other.getSkillKey());
      result = result && getData()
          .equals(other.getData());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + UTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUtime());
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion();
      hash = (37 * hash) + REQUEST_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRequestId());
      hash = (37 * hash) + ACK_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getAck());
      hash = (37 * hash) + SKILL_KEY_FIELD_NUMBER;
      hash = (53 * hash) + getSkillKey().hashCode();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * An RPC request message containing a skill destination and binary user data
     * </pre>
     *
     * Protobuf type {@code skills.CustomRpcRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:skills.CustomRpcRequest)
        com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.skydio.pbtypes.skills.CustomCommsProto.internal_static_skills_CustomRpcRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.skydio.pbtypes.skills.CustomCommsProto.internal_static_skills_CustomRpcRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcRequest.class, com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcRequest.Builder.class);
      }

      // Construct using com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        utime_ = 0L;

        version_ = 0;

        requestId_ = 0L;

        ack_ = false;

        skillKey_ = "";

        data_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.skydio.pbtypes.skills.CustomCommsProto.internal_static_skills_CustomRpcRequest_descriptor;
      }

      @java.lang.Override
      public com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcRequest getDefaultInstanceForType() {
        return com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcRequest build() {
        com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcRequest buildPartial() {
        com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcRequest result = new com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcRequest(this);
        result.utime_ = utime_;
        result.version_ = version_;
        result.requestId_ = requestId_;
        result.ack_ = ack_;
        result.skillKey_ = skillKey_;
        result.data_ = data_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcRequest) {
          return mergeFrom((com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcRequest other) {
        if (other == com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcRequest.getDefaultInstance()) return this;
        if (other.getUtime() != 0L) {
          setUtime(other.getUtime());
        }
        if (other.getVersion() != 0) {
          setVersion(other.getVersion());
        }
        if (other.getRequestId() != 0L) {
          setRequestId(other.getRequestId());
        }
        if (other.getAck() != false) {
          setAck(other.getAck());
        }
        if (!other.getSkillKey().isEmpty()) {
          skillKey_ = other.skillKey_;
          onChanged();
        }
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long utime_ ;
      /**
       * <pre>
       * utime of the message
       * </pre>
       *
       * <code>int64 utime = 1;</code>
       */
      public long getUtime() {
        return utime_;
      }
      /**
       * <pre>
       * utime of the message
       * </pre>
       *
       * <code>int64 utime = 1;</code>
       */
      public Builder setUtime(long value) {
        
        utime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * utime of the message
       * </pre>
       *
       * <code>int64 utime = 1;</code>
       */
      public Builder clearUtime() {
        
        utime_ = 0L;
        onChanged();
        return this;
      }

      private int version_ ;
      /**
       * <pre>
       * version of the message
       * </pre>
       *
       * <code>int32 version = 2;</code>
       */
      public int getVersion() {
        return version_;
      }
      /**
       * <pre>
       * version of the message
       * </pre>
       *
       * <code>int32 version = 2;</code>
       */
      public Builder setVersion(int value) {
        
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * version of the message
       * </pre>
       *
       * <code>int32 version = 2;</code>
       */
      public Builder clearVersion() {
        
        version_ = 0;
        onChanged();
        return this;
      }

      private long requestId_ ;
      /**
       * <pre>
       * A unique id for the request.  This will be copied into the response.
       * </pre>
       *
       * <code>int64 request_id = 3;</code>
       */
      public long getRequestId() {
        return requestId_;
      }
      /**
       * <pre>
       * A unique id for the request.  This will be copied into the response.
       * </pre>
       *
       * <code>int64 request_id = 3;</code>
       */
      public Builder setRequestId(long value) {
        
        requestId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * A unique id for the request.  This will be copied into the response.
       * </pre>
       *
       * <code>int64 request_id = 3;</code>
       */
      public Builder clearRequestId() {
        
        requestId_ = 0L;
        onChanged();
        return this;
      }

      private boolean ack_ ;
      /**
       * <pre>
       * If false, the vehicle won't send a response.
       * </pre>
       *
       * <code>bool ack = 4;</code>
       */
      public boolean getAck() {
        return ack_;
      }
      /**
       * <pre>
       * If false, the vehicle won't send a response.
       * </pre>
       *
       * <code>bool ack = 4;</code>
       */
      public Builder setAck(boolean value) {
        
        ack_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * If false, the vehicle won't send a response.
       * </pre>
       *
       * <code>bool ack = 4;</code>
       */
      public Builder clearAck() {
        
        ack_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object skillKey_ = "";
      /**
       * <pre>
       * The key of the skill which will receive this request.
       * If the given skill is not running, an error will be returned.
       * </pre>
       *
       * <code>string skill_key = 5;</code>
       */
      public java.lang.String getSkillKey() {
        java.lang.Object ref = skillKey_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          skillKey_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * The key of the skill which will receive this request.
       * If the given skill is not running, an error will be returned.
       * </pre>
       *
       * <code>string skill_key = 5;</code>
       */
      public com.google.protobuf.ByteString
          getSkillKeyBytes() {
        java.lang.Object ref = skillKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          skillKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * The key of the skill which will receive this request.
       * If the given skill is not running, an error will be returned.
       * </pre>
       *
       * <code>string skill_key = 5;</code>
       */
      public Builder setSkillKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        skillKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The key of the skill which will receive this request.
       * If the given skill is not running, an error will be returned.
       * </pre>
       *
       * <code>string skill_key = 5;</code>
       */
      public Builder clearSkillKey() {
        
        skillKey_ = getDefaultInstance().getSkillKey();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The key of the skill which will receive this request.
       * If the given skill is not running, an error will be returned.
       * </pre>
       *
       * <code>string skill_key = 5;</code>
       */
      public Builder setSkillKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        skillKey_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * The request data.
       * </pre>
       *
       * <code>bytes data = 6;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <pre>
       * The request data.
       * </pre>
       *
       * <code>bytes data = 6;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The request data.
       * </pre>
       *
       * <code>bytes data = 6;</code>
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:skills.CustomRpcRequest)
    }

    // @@protoc_insertion_point(class_scope:skills.CustomRpcRequest)
    private static final com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcRequest();
    }

    public static com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CustomRpcRequest>
        PARSER = new com.google.protobuf.AbstractParser<CustomRpcRequest>() {
      @java.lang.Override
      public CustomRpcRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CustomRpcRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CustomRpcRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CustomRpcRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CustomRpcResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:skills.CustomRpcResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * utime of the message
     * </pre>
     *
     * <code>int64 utime = 1;</code>
     */
    long getUtime();

    /**
     * <pre>
     * version of the message
     * </pre>
     *
     * <code>int32 version = 2;</code>
     */
    int getVersion();

    /**
     * <pre>
     * The unique id of the request to which this is a response.
     * </pre>
     *
     * <code>int64 request_id = 3;</code>
     */
    long getRequestId();

    /**
     * <pre>
     * Whether the call succeeded or why it failed.
     * </pre>
     *
     * <code>.skills.CustomRpcResponse.Status status = 4;</code>
     */
    int getStatusValue();
    /**
     * <pre>
     * Whether the call succeeded or why it failed.
     * </pre>
     *
     * <code>.skills.CustomRpcResponse.Status status = 4;</code>
     */
    com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcResponse.Status getStatus();

    /**
     * <pre>
     * The response data (or error data in some error cases).
     * </pre>
     *
     * <code>bytes data = 5;</code>
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * <pre>
   * An RPC response message containing a status and binary user data
   * </pre>
   *
   * Protobuf type {@code skills.CustomRpcResponse}
   */
  public  static final class CustomRpcResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:skills.CustomRpcResponse)
      CustomRpcResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CustomRpcResponse.newBuilder() to construct.
    private CustomRpcResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CustomRpcResponse() {
      utime_ = 0L;
      version_ = 0;
      requestId_ = 0L;
      status_ = 0;
      data_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CustomRpcResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              utime_ = input.readInt64();
              break;
            }
            case 16: {

              version_ = input.readInt32();
              break;
            }
            case 24: {

              requestId_ = input.readInt64();
              break;
            }
            case 32: {
              int rawValue = input.readEnum();

              status_ = rawValue;
              break;
            }
            case 42: {

              data_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.skydio.pbtypes.skills.CustomCommsProto.internal_static_skills_CustomRpcResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.skydio.pbtypes.skills.CustomCommsProto.internal_static_skills_CustomRpcResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcResponse.class, com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcResponse.Builder.class);
    }

    /**
     * <pre>
     * An enumeration of RPC status codes
     * </pre>
     *
     * Protobuf enum {@code skills.CustomRpcResponse.Status}
     */
    public enum Status
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>SUCCESS = 0;</code>
       */
      SUCCESS(0),
      /**
       * <pre>
       * codes sent by the vehicle which will not contain data
       * </pre>
       *
       * <code>MODE_NOT_ACTIVE = 1001;</code>
       */
      MODE_NOT_ACTIVE(1001),
      /**
       * <pre>
       * The skill has not registered an rpc handler
       * </pre>
       *
       * <code>NO_RPC_HANDLER = 1002;</code>
       */
      NO_RPC_HANDLER(1002),
      /**
       * <pre>
       * codes sent by the vehicle which include `data` that is not a response
       * </pre>
       *
       * <code>EXCEPTION = 1101;</code>
       */
      EXCEPTION(1101),
      /**
       * <pre>
       * the rpc handler on the vehicle returned a non-string type
       * </pre>
       *
       * <code>INVALID_TYPE = 1102;</code>
       */
      INVALID_TYPE(1102),
      /**
       * <pre>
       * codes returned by the phone service if the vehicle isn't
       * </pre>
       *
       * <code>RESPONSE_TIMEOUT = 2001;</code>
       */
      RESPONSE_TIMEOUT(2001),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>SUCCESS = 0;</code>
       */
      public static final int SUCCESS_VALUE = 0;
      /**
       * <pre>
       * codes sent by the vehicle which will not contain data
       * </pre>
       *
       * <code>MODE_NOT_ACTIVE = 1001;</code>
       */
      public static final int MODE_NOT_ACTIVE_VALUE = 1001;
      /**
       * <pre>
       * The skill has not registered an rpc handler
       * </pre>
       *
       * <code>NO_RPC_HANDLER = 1002;</code>
       */
      public static final int NO_RPC_HANDLER_VALUE = 1002;
      /**
       * <pre>
       * codes sent by the vehicle which include `data` that is not a response
       * </pre>
       *
       * <code>EXCEPTION = 1101;</code>
       */
      public static final int EXCEPTION_VALUE = 1101;
      /**
       * <pre>
       * the rpc handler on the vehicle returned a non-string type
       * </pre>
       *
       * <code>INVALID_TYPE = 1102;</code>
       */
      public static final int INVALID_TYPE_VALUE = 1102;
      /**
       * <pre>
       * codes returned by the phone service if the vehicle isn't
       * </pre>
       *
       * <code>RESPONSE_TIMEOUT = 2001;</code>
       */
      public static final int RESPONSE_TIMEOUT_VALUE = 2001;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Status valueOf(int value) {
        return forNumber(value);
      }

      public static Status forNumber(int value) {
        switch (value) {
          case 0: return SUCCESS;
          case 1001: return MODE_NOT_ACTIVE;
          case 1002: return NO_RPC_HANDLER;
          case 1101: return EXCEPTION;
          case 1102: return INVALID_TYPE;
          case 2001: return RESPONSE_TIMEOUT;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Status>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Status> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Status>() {
              public Status findValueByNumber(int number) {
                return Status.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcResponse.getDescriptor().getEnumTypes().get(0);
      }

      private static final Status[] VALUES = values();

      public static Status valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Status(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:skills.CustomRpcResponse.Status)
    }

    public static final int UTIME_FIELD_NUMBER = 1;
    private long utime_;
    /**
     * <pre>
     * utime of the message
     * </pre>
     *
     * <code>int64 utime = 1;</code>
     */
    public long getUtime() {
      return utime_;
    }

    public static final int VERSION_FIELD_NUMBER = 2;
    private int version_;
    /**
     * <pre>
     * version of the message
     * </pre>
     *
     * <code>int32 version = 2;</code>
     */
    public int getVersion() {
      return version_;
    }

    public static final int REQUEST_ID_FIELD_NUMBER = 3;
    private long requestId_;
    /**
     * <pre>
     * The unique id of the request to which this is a response.
     * </pre>
     *
     * <code>int64 request_id = 3;</code>
     */
    public long getRequestId() {
      return requestId_;
    }

    public static final int STATUS_FIELD_NUMBER = 4;
    private int status_;
    /**
     * <pre>
     * Whether the call succeeded or why it failed.
     * </pre>
     *
     * <code>.skills.CustomRpcResponse.Status status = 4;</code>
     */
    public int getStatusValue() {
      return status_;
    }
    /**
     * <pre>
     * Whether the call succeeded or why it failed.
     * </pre>
     *
     * <code>.skills.CustomRpcResponse.Status status = 4;</code>
     */
    public com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcResponse.Status getStatus() {
      @SuppressWarnings("deprecation")
      com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcResponse.Status result = com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcResponse.Status.valueOf(status_);
      return result == null ? com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcResponse.Status.UNRECOGNIZED : result;
    }

    public static final int DATA_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString data_;
    /**
     * <pre>
     * The response data (or error data in some error cases).
     * </pre>
     *
     * <code>bytes data = 5;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (utime_ != 0L) {
        output.writeInt64(1, utime_);
      }
      if (version_ != 0) {
        output.writeInt32(2, version_);
      }
      if (requestId_ != 0L) {
        output.writeInt64(3, requestId_);
      }
      if (status_ != com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcResponse.Status.SUCCESS.getNumber()) {
        output.writeEnum(4, status_);
      }
      if (!data_.isEmpty()) {
        output.writeBytes(5, data_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (utime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, utime_);
      }
      if (version_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, version_);
      }
      if (requestId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, requestId_);
      }
      if (status_ != com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcResponse.Status.SUCCESS.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, status_);
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, data_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcResponse)) {
        return super.equals(obj);
      }
      com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcResponse other = (com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcResponse) obj;

      boolean result = true;
      result = result && (getUtime()
          == other.getUtime());
      result = result && (getVersion()
          == other.getVersion());
      result = result && (getRequestId()
          == other.getRequestId());
      result = result && status_ == other.status_;
      result = result && getData()
          .equals(other.getData());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + UTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUtime());
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion();
      hash = (37 * hash) + REQUEST_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRequestId());
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + status_;
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * An RPC response message containing a status and binary user data
     * </pre>
     *
     * Protobuf type {@code skills.CustomRpcResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:skills.CustomRpcResponse)
        com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.skydio.pbtypes.skills.CustomCommsProto.internal_static_skills_CustomRpcResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.skydio.pbtypes.skills.CustomCommsProto.internal_static_skills_CustomRpcResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcResponse.class, com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcResponse.Builder.class);
      }

      // Construct using com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        utime_ = 0L;

        version_ = 0;

        requestId_ = 0L;

        status_ = 0;

        data_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.skydio.pbtypes.skills.CustomCommsProto.internal_static_skills_CustomRpcResponse_descriptor;
      }

      @java.lang.Override
      public com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcResponse getDefaultInstanceForType() {
        return com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcResponse build() {
        com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcResponse buildPartial() {
        com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcResponse result = new com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcResponse(this);
        result.utime_ = utime_;
        result.version_ = version_;
        result.requestId_ = requestId_;
        result.status_ = status_;
        result.data_ = data_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcResponse) {
          return mergeFrom((com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcResponse other) {
        if (other == com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcResponse.getDefaultInstance()) return this;
        if (other.getUtime() != 0L) {
          setUtime(other.getUtime());
        }
        if (other.getVersion() != 0) {
          setVersion(other.getVersion());
        }
        if (other.getRequestId() != 0L) {
          setRequestId(other.getRequestId());
        }
        if (other.status_ != 0) {
          setStatusValue(other.getStatusValue());
        }
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long utime_ ;
      /**
       * <pre>
       * utime of the message
       * </pre>
       *
       * <code>int64 utime = 1;</code>
       */
      public long getUtime() {
        return utime_;
      }
      /**
       * <pre>
       * utime of the message
       * </pre>
       *
       * <code>int64 utime = 1;</code>
       */
      public Builder setUtime(long value) {
        
        utime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * utime of the message
       * </pre>
       *
       * <code>int64 utime = 1;</code>
       */
      public Builder clearUtime() {
        
        utime_ = 0L;
        onChanged();
        return this;
      }

      private int version_ ;
      /**
       * <pre>
       * version of the message
       * </pre>
       *
       * <code>int32 version = 2;</code>
       */
      public int getVersion() {
        return version_;
      }
      /**
       * <pre>
       * version of the message
       * </pre>
       *
       * <code>int32 version = 2;</code>
       */
      public Builder setVersion(int value) {
        
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * version of the message
       * </pre>
       *
       * <code>int32 version = 2;</code>
       */
      public Builder clearVersion() {
        
        version_ = 0;
        onChanged();
        return this;
      }

      private long requestId_ ;
      /**
       * <pre>
       * The unique id of the request to which this is a response.
       * </pre>
       *
       * <code>int64 request_id = 3;</code>
       */
      public long getRequestId() {
        return requestId_;
      }
      /**
       * <pre>
       * The unique id of the request to which this is a response.
       * </pre>
       *
       * <code>int64 request_id = 3;</code>
       */
      public Builder setRequestId(long value) {
        
        requestId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The unique id of the request to which this is a response.
       * </pre>
       *
       * <code>int64 request_id = 3;</code>
       */
      public Builder clearRequestId() {
        
        requestId_ = 0L;
        onChanged();
        return this;
      }

      private int status_ = 0;
      /**
       * <pre>
       * Whether the call succeeded or why it failed.
       * </pre>
       *
       * <code>.skills.CustomRpcResponse.Status status = 4;</code>
       */
      public int getStatusValue() {
        return status_;
      }
      /**
       * <pre>
       * Whether the call succeeded or why it failed.
       * </pre>
       *
       * <code>.skills.CustomRpcResponse.Status status = 4;</code>
       */
      public Builder setStatusValue(int value) {
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Whether the call succeeded or why it failed.
       * </pre>
       *
       * <code>.skills.CustomRpcResponse.Status status = 4;</code>
       */
      public com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcResponse.Status getStatus() {
        @SuppressWarnings("deprecation")
        com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcResponse.Status result = com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcResponse.Status.valueOf(status_);
        return result == null ? com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcResponse.Status.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * Whether the call succeeded or why it failed.
       * </pre>
       *
       * <code>.skills.CustomRpcResponse.Status status = 4;</code>
       */
      public Builder setStatus(com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcResponse.Status value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        status_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Whether the call succeeded or why it failed.
       * </pre>
       *
       * <code>.skills.CustomRpcResponse.Status status = 4;</code>
       */
      public Builder clearStatus() {
        
        status_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * The response data (or error data in some error cases).
       * </pre>
       *
       * <code>bytes data = 5;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <pre>
       * The response data (or error data in some error cases).
       * </pre>
       *
       * <code>bytes data = 5;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The response data (or error data in some error cases).
       * </pre>
       *
       * <code>bytes data = 5;</code>
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:skills.CustomRpcResponse)
    }

    // @@protoc_insertion_point(class_scope:skills.CustomRpcResponse)
    private static final com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcResponse();
    }

    public static com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CustomRpcResponse>
        PARSER = new com.google.protobuf.AbstractParser<CustomRpcResponse>() {
      @java.lang.Override
      public CustomRpcResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CustomRpcResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CustomRpcResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CustomRpcResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.skydio.pbtypes.skills.CustomCommsProto.CustomRpcResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CustomSkillStatusOrBuilder extends
      // @@protoc_insertion_point(interface_extends:skills.CustomSkillStatus)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * utime of the message
     * </pre>
     *
     * <code>int64 utime = 1;</code>
     */
    long getUtime();

    /**
     * <pre>
     * version of the message
     * </pre>
     *
     * <code>int32 version = 2;</code>
     */
    int getVersion();

    /**
     * <pre>
     * The skill which sent the status
     * </pre>
     *
     * <code>string skill_key = 3;</code>
     */
    java.lang.String getSkillKey();
    /**
     * <pre>
     * The skill which sent the status
     * </pre>
     *
     * <code>string skill_key = 3;</code>
     */
    com.google.protobuf.ByteString
        getSkillKeyBytes();

    /**
     * <pre>
     * The binary status data
     * </pre>
     *
     * <code>bytes data = 4;</code>
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * <pre>
   * A message which just contains the skill which sent the status and binary user data
   * </pre>
   *
   * Protobuf type {@code skills.CustomSkillStatus}
   */
  public  static final class CustomSkillStatus extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:skills.CustomSkillStatus)
      CustomSkillStatusOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CustomSkillStatus.newBuilder() to construct.
    private CustomSkillStatus(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CustomSkillStatus() {
      utime_ = 0L;
      version_ = 0;
      skillKey_ = "";
      data_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CustomSkillStatus(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              utime_ = input.readInt64();
              break;
            }
            case 16: {

              version_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              skillKey_ = s;
              break;
            }
            case 34: {

              data_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.skydio.pbtypes.skills.CustomCommsProto.internal_static_skills_CustomSkillStatus_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.skydio.pbtypes.skills.CustomCommsProto.internal_static_skills_CustomSkillStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.skydio.pbtypes.skills.CustomCommsProto.CustomSkillStatus.class, com.skydio.pbtypes.skills.CustomCommsProto.CustomSkillStatus.Builder.class);
    }

    public static final int UTIME_FIELD_NUMBER = 1;
    private long utime_;
    /**
     * <pre>
     * utime of the message
     * </pre>
     *
     * <code>int64 utime = 1;</code>
     */
    public long getUtime() {
      return utime_;
    }

    public static final int VERSION_FIELD_NUMBER = 2;
    private int version_;
    /**
     * <pre>
     * version of the message
     * </pre>
     *
     * <code>int32 version = 2;</code>
     */
    public int getVersion() {
      return version_;
    }

    public static final int SKILL_KEY_FIELD_NUMBER = 3;
    private volatile java.lang.Object skillKey_;
    /**
     * <pre>
     * The skill which sent the status
     * </pre>
     *
     * <code>string skill_key = 3;</code>
     */
    public java.lang.String getSkillKey() {
      java.lang.Object ref = skillKey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        skillKey_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * The skill which sent the status
     * </pre>
     *
     * <code>string skill_key = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSkillKeyBytes() {
      java.lang.Object ref = skillKey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        skillKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATA_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString data_;
    /**
     * <pre>
     * The binary status data
     * </pre>
     *
     * <code>bytes data = 4;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (utime_ != 0L) {
        output.writeInt64(1, utime_);
      }
      if (version_ != 0) {
        output.writeInt32(2, version_);
      }
      if (!getSkillKeyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, skillKey_);
      }
      if (!data_.isEmpty()) {
        output.writeBytes(4, data_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (utime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, utime_);
      }
      if (version_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, version_);
      }
      if (!getSkillKeyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, skillKey_);
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, data_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.skydio.pbtypes.skills.CustomCommsProto.CustomSkillStatus)) {
        return super.equals(obj);
      }
      com.skydio.pbtypes.skills.CustomCommsProto.CustomSkillStatus other = (com.skydio.pbtypes.skills.CustomCommsProto.CustomSkillStatus) obj;

      boolean result = true;
      result = result && (getUtime()
          == other.getUtime());
      result = result && (getVersion()
          == other.getVersion());
      result = result && getSkillKey()
          .equals(other.getSkillKey());
      result = result && getData()
          .equals(other.getData());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + UTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUtime());
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion();
      hash = (37 * hash) + SKILL_KEY_FIELD_NUMBER;
      hash = (53 * hash) + getSkillKey().hashCode();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.skydio.pbtypes.skills.CustomCommsProto.CustomSkillStatus parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.skydio.pbtypes.skills.CustomCommsProto.CustomSkillStatus parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.skydio.pbtypes.skills.CustomCommsProto.CustomSkillStatus parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.skydio.pbtypes.skills.CustomCommsProto.CustomSkillStatus parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.skydio.pbtypes.skills.CustomCommsProto.CustomSkillStatus parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.skydio.pbtypes.skills.CustomCommsProto.CustomSkillStatus parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.skydio.pbtypes.skills.CustomCommsProto.CustomSkillStatus parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.skydio.pbtypes.skills.CustomCommsProto.CustomSkillStatus parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.skydio.pbtypes.skills.CustomCommsProto.CustomSkillStatus parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.skydio.pbtypes.skills.CustomCommsProto.CustomSkillStatus parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.skydio.pbtypes.skills.CustomCommsProto.CustomSkillStatus parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.skydio.pbtypes.skills.CustomCommsProto.CustomSkillStatus parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.skydio.pbtypes.skills.CustomCommsProto.CustomSkillStatus prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * A message which just contains the skill which sent the status and binary user data
     * </pre>
     *
     * Protobuf type {@code skills.CustomSkillStatus}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:skills.CustomSkillStatus)
        com.skydio.pbtypes.skills.CustomCommsProto.CustomSkillStatusOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.skydio.pbtypes.skills.CustomCommsProto.internal_static_skills_CustomSkillStatus_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.skydio.pbtypes.skills.CustomCommsProto.internal_static_skills_CustomSkillStatus_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.skydio.pbtypes.skills.CustomCommsProto.CustomSkillStatus.class, com.skydio.pbtypes.skills.CustomCommsProto.CustomSkillStatus.Builder.class);
      }

      // Construct using com.skydio.pbtypes.skills.CustomCommsProto.CustomSkillStatus.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        utime_ = 0L;

        version_ = 0;

        skillKey_ = "";

        data_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.skydio.pbtypes.skills.CustomCommsProto.internal_static_skills_CustomSkillStatus_descriptor;
      }

      @java.lang.Override
      public com.skydio.pbtypes.skills.CustomCommsProto.CustomSkillStatus getDefaultInstanceForType() {
        return com.skydio.pbtypes.skills.CustomCommsProto.CustomSkillStatus.getDefaultInstance();
      }

      @java.lang.Override
      public com.skydio.pbtypes.skills.CustomCommsProto.CustomSkillStatus build() {
        com.skydio.pbtypes.skills.CustomCommsProto.CustomSkillStatus result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.skydio.pbtypes.skills.CustomCommsProto.CustomSkillStatus buildPartial() {
        com.skydio.pbtypes.skills.CustomCommsProto.CustomSkillStatus result = new com.skydio.pbtypes.skills.CustomCommsProto.CustomSkillStatus(this);
        result.utime_ = utime_;
        result.version_ = version_;
        result.skillKey_ = skillKey_;
        result.data_ = data_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.skydio.pbtypes.skills.CustomCommsProto.CustomSkillStatus) {
          return mergeFrom((com.skydio.pbtypes.skills.CustomCommsProto.CustomSkillStatus)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.skydio.pbtypes.skills.CustomCommsProto.CustomSkillStatus other) {
        if (other == com.skydio.pbtypes.skills.CustomCommsProto.CustomSkillStatus.getDefaultInstance()) return this;
        if (other.getUtime() != 0L) {
          setUtime(other.getUtime());
        }
        if (other.getVersion() != 0) {
          setVersion(other.getVersion());
        }
        if (!other.getSkillKey().isEmpty()) {
          skillKey_ = other.skillKey_;
          onChanged();
        }
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.skydio.pbtypes.skills.CustomCommsProto.CustomSkillStatus parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.skydio.pbtypes.skills.CustomCommsProto.CustomSkillStatus) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long utime_ ;
      /**
       * <pre>
       * utime of the message
       * </pre>
       *
       * <code>int64 utime = 1;</code>
       */
      public long getUtime() {
        return utime_;
      }
      /**
       * <pre>
       * utime of the message
       * </pre>
       *
       * <code>int64 utime = 1;</code>
       */
      public Builder setUtime(long value) {
        
        utime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * utime of the message
       * </pre>
       *
       * <code>int64 utime = 1;</code>
       */
      public Builder clearUtime() {
        
        utime_ = 0L;
        onChanged();
        return this;
      }

      private int version_ ;
      /**
       * <pre>
       * version of the message
       * </pre>
       *
       * <code>int32 version = 2;</code>
       */
      public int getVersion() {
        return version_;
      }
      /**
       * <pre>
       * version of the message
       * </pre>
       *
       * <code>int32 version = 2;</code>
       */
      public Builder setVersion(int value) {
        
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * version of the message
       * </pre>
       *
       * <code>int32 version = 2;</code>
       */
      public Builder clearVersion() {
        
        version_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object skillKey_ = "";
      /**
       * <pre>
       * The skill which sent the status
       * </pre>
       *
       * <code>string skill_key = 3;</code>
       */
      public java.lang.String getSkillKey() {
        java.lang.Object ref = skillKey_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          skillKey_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * The skill which sent the status
       * </pre>
       *
       * <code>string skill_key = 3;</code>
       */
      public com.google.protobuf.ByteString
          getSkillKeyBytes() {
        java.lang.Object ref = skillKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          skillKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * The skill which sent the status
       * </pre>
       *
       * <code>string skill_key = 3;</code>
       */
      public Builder setSkillKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        skillKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The skill which sent the status
       * </pre>
       *
       * <code>string skill_key = 3;</code>
       */
      public Builder clearSkillKey() {
        
        skillKey_ = getDefaultInstance().getSkillKey();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The skill which sent the status
       * </pre>
       *
       * <code>string skill_key = 3;</code>
       */
      public Builder setSkillKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        skillKey_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * The binary status data
       * </pre>
       *
       * <code>bytes data = 4;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <pre>
       * The binary status data
       * </pre>
       *
       * <code>bytes data = 4;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The binary status data
       * </pre>
       *
       * <code>bytes data = 4;</code>
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:skills.CustomSkillStatus)
    }

    // @@protoc_insertion_point(class_scope:skills.CustomSkillStatus)
    private static final com.skydio.pbtypes.skills.CustomCommsProto.CustomSkillStatus DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.skydio.pbtypes.skills.CustomCommsProto.CustomSkillStatus();
    }

    public static com.skydio.pbtypes.skills.CustomCommsProto.CustomSkillStatus getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CustomSkillStatus>
        PARSER = new com.google.protobuf.AbstractParser<CustomSkillStatus>() {
      @java.lang.Override
      public CustomSkillStatus parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CustomSkillStatus(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CustomSkillStatus> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CustomSkillStatus> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.skydio.pbtypes.skills.CustomCommsProto.CustomSkillStatus getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_skills_CustomRpcRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_skills_CustomRpcRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_skills_CustomRpcResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_skills_CustomRpcResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_skills_CustomSkillStatus_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_skills_CustomSkillStatus_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022custom_comms.proto\022\006skills\"t\n\020CustomRp" +
      "cRequest\022\r\n\005utime\030\001 \001(\003\022\017\n\007version\030\002 \001(\005" +
      "\022\022\n\nrequest_id\030\003 \001(\003\022\013\n\003ack\030\004 \001(\010\022\021\n\tski" +
      "ll_key\030\005 \001(\t\022\014\n\004data\030\006 \001(\014\"\203\002\n\021CustomRpc" +
      "Response\022\r\n\005utime\030\001 \001(\003\022\017\n\007version\030\002 \001(\005" +
      "\022\022\n\nrequest_id\030\003 \001(\003\0220\n\006status\030\004 \001(\0162 .s" +
      "kills.CustomRpcResponse.Status\022\014\n\004data\030\005" +
      " \001(\014\"z\n\006Status\022\013\n\007SUCCESS\020\000\022\024\n\017MODE_NOT_" +
      "ACTIVE\020\351\007\022\023\n\016NO_RPC_HANDLER\020\352\007\022\016\n\tEXCEPT" +
      "ION\020\315\010\022\021\n\014INVALID_TYPE\020\316\010\022\025\n\020RESPONSE_TI" +
      "MEOUT\020\321\017\"T\n\021CustomSkillStatus\022\r\n\005utime\030\001" +
      " \001(\003\022\017\n\007version\030\002 \001(\005\022\021\n\tskill_key\030\003 \001(\t" +
      "\022\014\n\004data\030\004 \001(\014B-\n\031com.skydio.pbtypes.ski" +
      "llsB\020CustomCommsProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_skills_CustomRpcRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_skills_CustomRpcRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_skills_CustomRpcRequest_descriptor,
        new java.lang.String[] { "Utime", "Version", "RequestId", "Ack", "SkillKey", "Data", });
    internal_static_skills_CustomRpcResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_skills_CustomRpcResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_skills_CustomRpcResponse_descriptor,
        new java.lang.String[] { "Utime", "Version", "RequestId", "Status", "Data", });
    internal_static_skills_CustomSkillStatus_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_skills_CustomSkillStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_skills_CustomSkillStatus_descriptor,
        new java.lang.String[] { "Utime", "Version", "SkillKey", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
